include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    require_trailing_commas: false
    avoid_multiple_declarations_per_line: false
