name: universal_tpms_reader
description: Universal BLE tire pressor sensor reader

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  app_settings: 4.2.0
  avatar_glow: 2.0.2
  bloc_concurrency: 0.2.0
  change: 0.5.0
  collection: 1.17.0
  convert: 3.1.1
  dart_extensions: 2.2.0
  device_info_plus: 8.0.0
  dotted_border: 2.0.0+3
  easy_localization: 3.0.1
  fast_immutable_collections: 8.1.1
  fluent_ui: 4.2.0
  fluentui_system_icons: 1.1.190
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.1
  flutter_colorpicker: 1.0.3
  flutter_layout_grid: 2.0.1
  flutter_native_splash: 2.2.16
  flutter_reactive_ble: 5.0.3
  flutter_svg: 1.1.6
  freezed_annotation: 2.2.0
  get_it: 7.2.0
  glowstone: 0.0.2
  isar: 3.0.5
  isar_flutter_libs: 3.0.5
  lottie: 2.2.0
  morphable_shape: 1.6.4
  package_info_plus: 3.0.2
  path: 1.8.2
  path_provider: 2.0.12
  permission_handler: 10.2.0
  responsive_grid: 2.1.0
  restart_app: 1.1.1+1
  routemaster: 1.0.1
  shared_preferences: 2.0.17
  step_progress_indicator: 1.0.2
  system_theme: 2.1.0
  uuid: 3.0.7
  wakelock: 0.6.2

dev_dependencies:
  build_runner: 2.3.3
  dart_code_metrics: 5.5.0
  flutter_test:
    sdk: flutter
  freezed: 2.3.2
  isar_generator: 3.0.5
  lint: 2.0.1

flutter:
  uses-material-design: true

  assets:
    - CHANGELOG.md
    - assets/icons/
    - assets/lottie/
    - assets/translations/
