name: universal_tpms_reader
description: Universal BLE tire pressor sensor reader

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  app_settings: 4.1.8
  avatar_glow: 2.0.2
  bloc_concurrency: 0.2.0
  change: 0.4.0
  collection: 1.16.0
  convert: 3.0.2
  dart_extensions: 2.2.0
  device_info_plus: 4.1.2
  dotted_border: 2.0.0+2
  easy_localization: 3.0.1
  fast_immutable_collections: 7.4.2
  fluent_ui: 4.0.0
  fluentui_system_icons: 1.1.181
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.1
  flutter_colorpicker: 1.0.3
  flutter_layout_grid: 2.0.1
  flutter_native_splash: 2.2.10
  flutter_reactive_ble: 5.0.2
  flutter_svg: 1.1.5
  freezed_annotation: 2.1.0
  get_it: 7.2.0
  glowstone: 0.0.2
  isar: 3.0.0
  isar_flutter_libs: 3.0.0
  lottie: 1.4.3
  morphable_shape: 1.6.4
  package_info_plus: 1.4.3+1
  path: 1.8.2
  path_provider: 2.0.11
  permission_handler: 10.0.1
  quick_blue: 0.5.0-dev.2
  responsive_grid: 2.1.0
  restart_app: 1.1.0+1
  routemaster: 1.0.1
  shared_preferences: 2.0.15
  step_progress_indicator: 1.0.2
  system_theme: 2.0.0
  uuid: 3.0.6
  wakelock: 0.6.2

dependency_overrides:
  analyzer: 4.6.0 # remove after updating isar, when this issue fixed: https://github.com/isar/isar/issues/719
  bluez: 0.8.0 # temporary till quick_blue updated its bluez dependency version

dev_dependencies:
  build_runner: 2.2.1
  flutter_test:
    sdk: flutter
  freezed: 2.1.1
  isar_generator: 3.0.0
  lint: 1.10.0

flutter:
  uses-material-design: true

  assets:
    - CHANGELOG.md
    - assets/icons/
    - assets/lottie/
    - assets/translations/
