name: universal_tpms_reader
description: Universal BLE tire pressor sensor reader

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  app_settings: 5.1.1
  avatar_glow: 2.0.2
  bloc_concurrency: 0.2.2
  change: 0.7.2
  collection: 1.17.2
  convert: 3.1.1
  dart_extensions: 2.2.2
  device_info_plus: 8.2.2
  dotted_border: 2.1.0
  easy_localization: 3.0.3
  fast_immutable_collections: 7.4.1
  fluent_ui: 4.7.6
  fluentui_system_icons: 1.1.219
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.3
  flutter_colorpicker: 1.0.3
  flutter_layout_grid: 2.0.5
  flutter_native_splash: 2.2.4
  flutter_reactive_ble: 5.2.0
  flutter_svg: 2.0.7
  freezed_annotation: 2.4.1
  get_it: 7.6.4
  glowstone: 0.0.2
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  lottie: 2.6.0
  morphable_shape: 1.6.6
  package_info_plus: 3.1.2
  path: 1.8.3
  path_provider: 2.1.1
  permission_handler: 11.0.1
  responsive_grid: 2.4.4
  restart_app: 1.2.1
  routemaster: 1.0.1
  shared_preferences: 2.2.2
  step_progress_indicator: 1.0.2
  system_theme: 2.3.1
  uuid: 4.1.0
  wakelock: 0.6.2

dev_dependencies:
  build_runner: 2.4.6
  flutter_test:
    sdk: flutter
  freezed: 2.4.5
  isar_generator: 3.1.0+1
  flutter_lints: 3.0.0

flutter:
  uses-material-design: true

  assets:
    - CHANGELOG.md
    - assets/icons/
    - assets/lottie/
    - assets/translations/
