name: universal_tpms_reader
description: Universal BLE tire pressor sensor reader

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  app_settings: 4.1.6
  avatar_glow: 2.0.2
  bloc_concurrency: 0.2.0
  change: 0.4.0
  convert: 3.0.1
  dart_extensions: 2.2.0
  dotted_border: 2.0.0+2
  easy_localization: 3.0.1-dev
  fast_immutable_collections: 7.3.1
  fluent_ui:
    git:
      url: https://github.com/h3x4d3c1m4l/fluent_ui.git
      ref: bugfix/flutter_3.0.0
  fluentui_system_icons: 1.1.168
  flutter:
    sdk: flutter
  flutter_bloc: 8.0.1
  flutter_colorpicker: 1.0.3
  flutter_layout_grid: 2.0.1
  flutter_native_splash: 2.1.6
  flutter_reactive_ble: 5.0.2
  flutter_svg: 1.0.3
  freezed_annotation: 2.0.3
  get_it: 7.2.0
  glowstone: 0.0.2
  isar: 2.5.0
  isar_flutter_libs: 2.5.0
  lottie: 1.3.0
  morphable_shape: 1.6.4
  package_info_plus: 1.4.2
  path_provider: 2.0.10
  permission_handler: 9.2.0
  quick_blue: 0.4.1+1
  responsive_grid: 2.1.0
  routemaster: 1.0.0
  shared_preferences: 2.0.15
  step_progress_indicator: 1.0.2
  system_theme: 2.0.0
  uuid: 3.0.6
  wakelock: 0.6.1+2

dev_dependencies:
  build_runner: 2.1.10
  flutter_test:
    sdk: flutter
  freezed: 2.0.3
  isar_generator: 2.5.0
  lint: 1.8.2

flutter:
  uses-material-design: true

  assets:
    - CHANGELOG.md
    - assets/translations/en.json
    - assets/translations/nl.json
    - assets/lottie/81848-spinning-wheel.json
    - assets/icons/led_green.svg
    - assets/icons/led_orange.svg
    - assets/icons/led_red.svg
    - assets/icons/led_off.svg
