name: universal_tpms_reader
description: Universal BLE tire pressor sensor reader

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  avatar_glow: 2.0.2
  bloc_concurrency: 0.2.0
  dart_extensions: 2.2.0
  dotted_border: 2.0.0+2
  easy_localization: 3.0.0
  fast_immutable_collections: 7.2.1
  fluent_ui: 3.10.0
  fluentui_system_icons: 1.1.163
  flutter_bloc: 8.0.1
  flutter_colorpicker: 1.0.3
  flutter_layout_grid: 1.0.6
  flutter_native_splash: 2.1.3+1
  flutter_reactive_ble: 5.0.2
  flutter_svg: 1.0.3
  freezed_annotation: 1.1.0
  glowstone: 0.0.2
  isar: 2.2.1
  isar_flutter_libs: 2.2.1
  lottie: 1.2.2
  mobile_scanner: 1.0.0
  morphable_shape: 1.6.4
  path_provider: 2.0.9
  permission_handler: 9.2.0
  responsive_grid: 2.0.0
  routemaster: 0.9.5
  quick_blue: 0.4.1+1
  shared_preferences: 2.0.13
  system_theme: 2.0.0
  uuid: 3.0.6
  wakelock: 0.6.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.1.8
  flutter_lints: 1.0.4
  freezed: 1.1.1
  isar_generator: 2.2.1

flutter:
  uses-material-design: true

  assets:
    - assets/translations/en.json
    - assets/translations/nl.json
    - assets/lottie/81848-spinning-wheel.json
    - assets/icons/led_green.svg
    - assets/icons/led_orange.svg
    - assets/icons/led_red.svg
    - assets/icons/led_off.svg
